import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { address, assertTestnet, horizon, i128, readAs, u32, usdcBalance, USDC_ISSUER } from './lib/soroban.mjs';
import { toUnits } from './lib/amounts.mjs';
const proof = JSON.parse(await readFile(process.argv[2] ? resolve(process.argv[2]) : new URL('../deployments/browser-testnet.json', import.meta.url), 'utf8'));
await assertTestnet();
const config = await readAs(proof.treasury, 'config');
assert.equal(config.admin, proof.accounts.admin);
assert.equal(config.vault, proof.vault);
assert.equal(config.quorum, 2);
const members = await readAs(proof.treasury, 'members');
for (const account of Object.values(proof.accounts)) assert(members.includes(account));
const proposal = await readAs(proof.treasury, 'proposal', [u32(1)]);
assert.equal(proposal.status[0], 'Executed');
assert.equal(proposal.payee, proof.accounts.payee);
const votes = await readAs(proof.treasury, 'approvals', [u32(1)]);
assert(votes.includes(proof.accounts.resident));
assert(votes.includes(proof.accounts.admin));
const shares = await readAs(proof.vault, 'balance', [address(proof.treasury)]);
const backing = (await readAs(proof.vault, 'get_asset_amounts_per_shares', [i128(shares)]))[0];
const deposit = proof.flows.find(flow => flow.kind === 'deposit');
const withdrawal = proof.flows.find(flow => flow.kind === 'withdraw');
assert.equal(backing, toUnits(deposit.amountOut) - proposal.amount);
assert.equal(await readAs(proof.treasury, 'balance'), backing);
assert.equal(await readAs(proof.treasury, 'liquid_balance'), 0n);
assert.equal(toUnits(await usdcBalance(proof.accounts.resident)), 0n);
assert.equal(toUnits(await usdcBalance(proof.accounts.payee)), 0n);
const hashes = new Set([...proof.transactions.map(tx => tx.hash), ...proof.flows.map(flow => flow.settlementHash)]);
for (const hash of hashes) assert.equal((await horizon.transactions().transaction(hash).call()).successful, true);
const payment = await horizon.transactions().transaction(withdrawal.receipt).call();
assert.equal(payment.memo_type, 'id'); assert.equal(payment.memo, withdrawal.memo);
const ops = await horizon.operations().forTransaction(withdrawal.receipt).call();
assert(ops.records.some(op => op.type === 'payment' && op.to === withdrawal.destination && op.from === proof.accounts.payee && op.asset_issuer === USDC_ISSUER && toUnits(op.amount) === toUnits(withdrawal.amountIn)));
console.log(`Browser demo verified: ${hashes.size} successful receipts, three members, two approvals, vault backing and exact bank payment.`);
console.log(`Treasury: ${proof.treasury}`);
